steps:
- bash: |
    set -x
    cd release
    npm install
    ls
    node createAdoPrs.js
  displayName: Create PRs in AzureDevOps and ConfigChange
  env:
    USER: $(User)
    PAT: $(AdoPAT)
    EMAIL: $(Email)
